version: "3.4"

services:
  shopping-lists:
    build: shopping-lists
    image: shopping-lists
    restart: "no"
    volumes:
      - ./shopping-lists/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-p1-06503d05-c6de-41c5-bd81-5594476e3458
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:latest
    platform: linux/arm64/v8
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - shopping-lists
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
